# Generated by Django 3.1.6 on 2021-05-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Centre_titre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('Numero_inventaire_entre', models.IntegerField(max_length=6)),
                ('Designation_Object', models.CharField(max_length=100)),
                ('Category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.categorymodel')),
                ('Quantite', models.IntegerField()),
                ('Emplacement', models.CharField(max_length=100)),
                ('Date_reception', models.DateTimeField(auto_now_add=True)),
                ('Prix_achat_unite', models.FloatField()),
                ('Prix_achat_total', models.FloatField()),
                ('Marque', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Serie', models.CharField(max_length=100)),
                ('Observation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SousCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sous_centre_titre', models.CharField(max_length=100)),
                ('centre_titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.affectation')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_inventaire_sortie', models.IntegerField(max_length=6)),
                ('Titre_livraison', models.CharField(max_length=100)),
                ('Date_sortie', models.DateTimeField(auto_now_add=True)),
                ('Quantite_livree', models.IntegerField()),
                ('Prix_unitaire', models.FloatField()),
                ('Decompte', models.CharField(max_length=100)),
                ('Signatures', models.CharField(max_length=100)),
                ('Affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.affectation')),
                ('Materiel_id', models.ManyToManyField(to='main_app.Materiel')),
            ],
        ),
    ]
