# Generated by Django 3.1.6 on 2021-05-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210517_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='Materiel',
            field=models.ManyToManyField(blank=True, to='main_app.MaterielModel'),
        ),
    ]
