# Generated by Django 3.1.6 on 2021-05-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210517_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='Materiel',
            field=models.ManyToManyField(related_name='MaterielModel_id', to='main_app.MaterielModel'),
        ),
    ]
