# Generated by Django 3.1.6 on 2021-05-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210518_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='Materiel',
            field=models.ManyToManyField(related_name='Materiel_id', to='main_app.MaterielModel'),
        ),
    ]
