# Generated by Django 3.1.6 on 2021-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210518_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='Centre_titre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
